[general]
name = "minilib-collection"
version = "0.7.0-alpha1"
fix_version = "1.2.0"
authors = ["pt9999"]
license = "MIT"

[build]
opt_level = "basic"
files = [
    "lib/collection/deque.fix",
    "lib/collection/ordered_map.fix",
    "lib/collection/ptree_map.fix",
    "lib/collection/ptree_set.fix",
    "lib/collection/treap_set.fix",
    "lib/collection/tree_map.fix",
    "lib/collection/tree_set.fix",
    "lib/collection/internal/pattree.fix",
    "lib/collection/internal/rbtree.fix",
    "lib/collection/trait/set.fix",
    "lib/collection/trait/map.fix",
    "lib/collection/trait/sorted_set.fix",
    "lib/collection/trait/sorted_map.fix",
]

[build.test]
opt_level = "basic"
files = [
    "tests/test.fix",
    "tests/collection/deque_test.fix",
    "tests/collection/ordered_map_test.fix",
    "tests/collection/ptree_map_test.fix",
    "tests/collection/ptree_set_test.fix",
    "tests/collection/treap_set_test.fix",
    "tests/collection/tree_map_test.fix",
    "tests/collection/tree_set_test.fix",
    "tests/collection/internal/pattree_test.fix",
    "tests/collection/internal/rbtree_test.fix",
    "tests/collection/trait/map_tests.fix",
    "tests/collection/trait/set_tests.fix",
    "tests/collection/trait/sorted_map_tests.fix",
    "tests/collection/trait/sorted_set_tests.fix",
    "tests/testing/test_util_array.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
# path = "../fixlang-minilib-common"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }


[[dependencies]]
name = "hashmap"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hashmap.git" }

# for test_util_array.fix
[[dependencies]]
name = "random"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-random.git" }
